# Generated by Django 5.2.6 on 2025-09-25 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(max_length=1024, unique=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('is_relevant', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execute_time', models.FloatField(blank=True, help_text='Tiempo total de ejecución en segundos', null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('RUNNING', 'En Ejecución'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='PENDING', max_length=10)),
                ('initial_results_count', models.PositiveIntegerField(default=0, help_text='Número total de resultados de búsqueda iniciales (web + RSS)')),
                ('relevant_results_count', models.PositiveIntegerField(default=0, help_text='Número de resultados considerados relevantes por el escrutinador')),
                ('opportunities_found_count', models.PositiveIntegerField(default=0, help_text='Número final de oportunidades extraídas')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='researches', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(help_text='Ruta al archivo del reporte generado', max_length=1024)),
                ('research', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='projects.research')),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('financing', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('url_to', models.URLField(max_length=1024)),
                ('type', models.CharField(max_length=100)),
                ('source_context', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='projects.itemcontext')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='projects.research')),
            ],
        ),
        migrations.AddField(
            model_name='itemcontext',
            name='research',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='projects.research'),
        ),
    ]
