# Generated by Django 5.2.6 on 2025-09-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_itemcontext_note_research_report_opportunity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcontext',
            name='summary',
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='requirements',
            field=models.JSONField(default=list, help_text="Una lista de de requerimientos principales , ej: ['.....', '.....']"),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='url_to',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
